# PoeThePoet task definitions
# https://poethepoet.natn.io/

[tool.poe.tasks]

# Linting and formatting
lint = "ruff check ."
format = "ruff format ."
format-check = "ruff format --check ."

# Testing  
test = "pytest"
test-fast = "pytest -x"
test-cov = "pytest --cov=reeltrust --cov-report=html"
test-unit = "pytest -m unit"
test-integration = "pytest -m integration"

# Combined tasks
check = ["format-check", "lint", "deps", "test"]
fix = ["format", "lint --fix"]

# Build and install
install = "uv sync --extra dev"
install-prod = "uv sync"
build = "uv build"

# Documentation (placeholder for future)
docs = "echo 'Documentation generation not yet configured'"
docs-serve = "echo 'Documentation serving not yet configured'"

# Development helpers
clean = "rm -rf .pytest_cache .coverage htmlcov dist .ruff_cache"
version = { "shell" = "echo 'reeltrust version:' && python -c 'import reeltrust; print(reeltrust.__version__)'" }

[tool.poe.tasks.typecheck]
help = "Run type checking with mypy"
cmd = "echo 'Type checking not yet configured - consider adding mypy'"

[tool.poe.tasks.security]
help = "Run security checks with bandit"  
cmd = "echo 'Security scanning not yet configured - consider adding bandit'"

[tool.poe.tasks.deps]
help = "Check for unused and missing dependencies"
cmd = "deptry ."

# Pre-commit style combined task
[tool.poe.tasks.pre-commit]
help = "Run all pre-commit checks"
sequence = ["format", "lint", "test-fast"]